# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

DEx_Rcpp <- function(PointNum, FactorNum, PosNum, ParticleNum, IterationNum, PValue, pMut, pCR, pGBest, pSelf, type, seed, maxTime = 1800L, maxNoImprove = 100L) {
    .Call(`_Meta4Design_DEx_Rcpp`, PointNum, FactorNum, PosNum, ParticleNum, IterationNum, PValue, pMut, pCR, pGBest, pSelf, type, seed, maxTime, maxNoImprove)
}

TAx_Rcpp <- function(PointNum, FactorNum, PosNum, ParticleNum, IterationNum, PValue, vT, SA, type, seed, maxTime = 1800L, maxNoImprove = 100L) {
    .Call(`_Meta4Design_TAx_Rcpp`, PointNum, FactorNum, PosNum, ParticleNum, IterationNum, PValue, vT, SA, type, seed, maxTime, maxNoImprove)
}

GAx_Rcpp <- function(PointNum, FactorNum, PosNum, PopulationNum, IterationNum, PValue, pMut, type, seed, maxTime = 1800L, maxNoImprove = 100L) {
    .Call(`_Meta4Design_GAx_Rcpp`, PointNum, FactorNum, PosNum, PopulationNum, IterationNum, PValue, pMut, type, seed, maxTime, maxNoImprove)
}

SRSx_Rcpp <- function(PointNum, FactorNum, PosNum, PopulationNum, IterationNum, PValue, type, seed, maxTime = 1800L, maxNoImprove = 100L) {
    .Call(`_Meta4Design_SRSx_Rcpp`, PointNum, FactorNum, PosNum, PopulationNum, IterationNum, PValue, type, seed, maxTime, maxNoImprove)
}

GeneticAlg_YY <- function(n, m, s, gmp_beta, popSize, elitism_ratio, crossover_ratio, mutation_prob, maxiter, type, verbose = FALSE) {
    .Call(`_Meta4Design_GeneticAlg_YY`, n, m, s, gmp_beta, popSize, elitism_ratio, crossover_ratio, mutation_prob, maxiter, type, verbose)
}

GeneticAlg_base <- function(n, m, s, beta, popSize, pMut, maxiter, type, verbose) {
    .Call(`_Meta4Design_GeneticAlg_base`, n, m, s, beta, popSize, pMut, maxiter, type, verbose)
}

test <- function(a) {
    .Call(`_Meta4Design_test`, a)
}

PSOx_Rcpp <- function(PointNum, FactorNum, PosNum, ParticleNum, IterationNum, PValue, SameNumP, SameNumG, pMut, SwapNumR, pGBest, pPBest, type, seed, maxTime = 1800L, maxNoImprove = 100L) {
    .Call(`_Meta4Design_PSOx_Rcpp`, PointNum, FactorNum, PosNum, ParticleNum, IterationNum, PValue, SameNumP, SameNumG, pMut, SwapNumR, pGBest, pPBest, type, seed, maxTime, maxNoImprove)
}

Move2Best_Rcpp <- function(PosNum, PointNum, SameNum, vParticle, vBest) {
    .Call(`_Meta4Design_Move2Best_Rcpp`, PosNum, PointNum, SameNum, vParticle, vBest)
}

gmp_log <- function(D, beta) {
    .Call(`_Meta4Design_gmp_log`, D, beta)
}

gmp <- function(D, beta) {
    .Call(`_Meta4Design_gmp`, D, beta)
}

gmp_diff <- function(D, i0, j0, k0, beta = 1.0) {
    .Call(`_Meta4Design_gmp_diff`, D, i0, j0, k0, beta)
}

phip_log <- function(D, p = 15) {
    .Call(`_Meta4Design_phip_log`, D, p)
}

phip <- function(D, p = 15) {
    .Call(`_Meta4Design_phip`, D, p)
}

phip_diff <- function(D, i0, j0, k0, p = 15) {
    .Call(`_Meta4Design_phip_diff`, D, i0, j0, k0, p)
}

crt_log <- function(D, beta, type) {
    .Call(`_Meta4Design_crt_log`, D, beta, type)
}

crt_diff <- function(D, i0, j0, k0, beta, type) {
    .Call(`_Meta4Design_crt_diff`, D, i0, j0, k0, beta, type)
}

generate_rbdesign <- function(n, m, s) {
    .Call(`_Meta4Design_generate_rbdesign`, n, m, s)
}

SA_XY <- function(n, m, s, beta, Ntrials, itermax, maxTime, T0, Npairs, nFail, type, verbose) {
    .Call(`_Meta4Design_SA_XY`, n, m, s, beta, Ntrials, itermax, maxTime, T0, Npairs, nFail, type, verbose)
}

SA_MM <- function(n, m, s, beta, Ntrials, itermax, maxTime, T0, Imax, nFail, type, verbose) {
    .Call(`_Meta4Design_SA_MM`, n, m, s, beta, Ntrials, itermax, maxTime, T0, Imax, nFail, type, verbose)
}

bid_log <- function(D, beta) {
    .Call(`_Meta4Design_bid_log`, D, beta)
}

bid <- function(D, beta) {
    .Call(`_Meta4Design_bid`, D, beta)
}

